include = ["**/*.toml"]
exclude = [
  "build/**",
  "packages/**/build/**",
  "manifest.toml",
  "packages/**/manifest.toml",
]

[formatting]
align_entries = false
array_auto_collapse = false
column_width = 100
reorder_keys = false
