version = 1

[[annotations]]
path = [
  ".github/**",
  ".gitleaks*",
  ".osv-scanner.toml",
  ".semgrep.yml",
  ".gitignore",
  ".markdownlint-cli2.yaml",
  ".mise.toml",
  ".taplo.toml",
  "_typos.toml",
  "*.md",
  "*.toml",
  "mix.lock",
  "LICENSE",
  "api/**",
  "benchmarks/**",
  "docs/**",
  "packages/**",
  "src/**",
  "test/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 the http3 contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"
